; Source: @digitalm1nd on x.com / _dek on Discord — Preservation Conquer project — https://discord.gg/CvKPXEHYRY
[Character]
Name=dek
Guild=Elite
GuildRank=Guild Leader
Body=3
Armor=130109
RightWeapon=410339
LeftWeapon=410339
Hair=910
Health=1000
MaximumHealth=1000
